name: 'Build Rslib'
description: 'Checkout, build rslib'
inputs:
  repository:
    description: 'The rslib repository to use'
    required: true
    default: 'web-infra-dev/rslib'
  path:
    description: 'Destination path to the rslib repository'
    required: true
    default: 'workspace/rslib'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
outputs:
  artifact-name:
    description: 'The name of the uploaded artifact'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24.20.0
    - shell: bash
      name: Install package manager
      run: |
        npm install -g corepack@latest --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: Checkout Rslib repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - name: Build Rslib
      shell: bash
      run: |
        cd ${{ inputs.path }}
        pnpm i
        node --run build
