# integration tests for rspress ecosystem - run per commit pushed to upstream main
name: rspress-ecosystem-ci-from-commit

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  workflow_dispatch:
    inputs:
      commitSHA:
        description: 'commit sha'
        required: true
        type: string
      repo:
        description: 'rspress repository to use'
        required: true
        type: string
        default: 'web-infra-dev/rspress'
      suite:
        description: 'testsuite to run. runs all test suites when `-`.'
        required: false
        type: choice
        options:
          - '-'
          - rsbuild
          - rslib
          - rspack
          - rspress-plugins
          - rstest
          - rstack-cli
      suiteRefType:
        description: 'type of suite ref to use'
        required: true
        type: choice
        options:
          - precoded
          - branch
          - tag
          - commit
        default: 'precoded'
      suiteRef:
        description: 'suite ref to use'
        required: true
        type: string
        default: 'precoded'
      updateComment:
        description: 'update comment'
        required: false
        type: boolean
        default: false
      distinct_id:
        description: 'Distinct ID injected by return-dispatch to identify this run'
        required: false
        type: string
        default: ''

jobs:
  return-dispatch-id:
    permissions: {}
    name: Return Dispatch ID
    runs-on: ubuntu-latest
    steps:
      - name: Return Dispatch ID ${{ inputs.distinct_id }}
        run: echo "${DISTINCT_ID}"
        env:
          DISTINCT_ID: ${{ inputs.distinct_id }}

  execute-selected-suite:
    runs-on: ubuntu-latest
    if: "inputs.suite != '-'"
    env:
      ECOSYSTEM_CI_REF: ${{ inputs.commitSHA }}
      ECOSYSTEM_CI_TYPE: 'commit'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/build-rspress
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commitSHA }}
      - run: pnpm i --frozen-lockfile
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@04d248b84655b509d8c44dc1d6f990c879747487 # v4
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          --stack rspress
          --suite-${{ inputs.suiteRefType }} ${{ inputs.suiteRef }}
          ${{ inputs.suite }}

  execute-all:
    if: "inputs.suite == '-'"
    strategy:
      matrix:
        include:
          - suite: rsbuild
            os: ubuntu-latest
          - suite: rslib
            os: ubuntu-latest
          - suite: rspack
            os: ubuntu-latest
          - suite: rspress-plugins
            os: ubuntu-latest
          - suite: rstest
            os: ubuntu-latest
          - suite: rstack-cli
            os: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: execute-all (${{ matrix.suite }})
    env:
      ECOSYSTEM_CI_REF: ${{ inputs.commitSHA }}
      ECOSYSTEM_CI_TYPE: 'commit'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1
      - uses: ./.github/actions/build-rspress
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commitSHA }}
      - run: pnpm i --frozen-lockfile
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@04d248b84655b509d8c44dc1d6f990c879747487 # v4
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          --stack rspress
          ${{ matrix.suite }}

  update-history:
    needs: [execute-all]
    if: ${{ always() && inputs.suite == '-' }}
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/_update-history.yml
    with:
      stack: rspress
      repo: ${{ inputs.repo }}
      commitSHA: ${{ inputs.commitSHA }}
